title: Net Zero Toolkit
description: The website for the toolkit that accompany the Scottish Episcopal Church's Net Zero Action Plan (2023-2030)
baseurl: "."
url: "https://robwoodford.github.io/SEC-Card-Game-staging"
repository: robwoodford/SEC-Card-Game-staging # for github-metadata
theme: just-the-docs
logo: ./graphics/site-logo.png

aux_links: none
nav_external_links: none

collections_dir: collections

collections:
  petals:
    output: true
  tasks:
    output: true
  cards:
    output: true
  steps:
    output: true
  tags:
    output: false
  links:
    output: true

# The navigation for each collection is a separate name space from page titles.
# A page in one collection cannot be a child of a page in a different collection, or of a normal page.

      # Exclude the collection from the navigation
      # Supports true or false (default)
      # nav_exclude: true
      # Fold the collection in the navigation
      # Supports true or false (default)
      # nav_fold: true  # note: this option is new in v0.4
      # Exclude the collection from the search
      # Supports true or false (default)
      # search_exclude: true

just_the_docs:
  collections:
    petals:
      name: Petals
      nav_exclude: false
    tasks:
      name: Tasks
      nav_exclude: true
    cards:
      name: Cards
      nav_exclude: true
    steps:
      name: Steps
      nav_exclude: true
    tags:
      name: Tags
      nav_exclude: true
    links:
      name: Links
      nav_exclude: true
      # possible we should search_exclude_true

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red


exclude:
  - aux
  - Gemfile
  - Gemfile.lock
  - README.md
  - 00notes.txt
  - junk 
  - _data-junk  
